FROM ruby:3.4.2

# Install system dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

# Create a non-root user
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID appuser && \
    useradd -m -u $UID -g $GID -s /bin/bash appuser

# Set the working directory
WORKDIR /opt/app

# Copy application dependency files (Gemfile) and install gems
COPY --chown=appuser:appuser Gemfile Gemfile.lock ./
USER appuser
RUN bundle install

# Copy the application code
COPY --chown=appuser:appuser . .

# Copy the entrypoint script and ensure it's executable
COPY --chown=appuser:appuser entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

# Expose the Rails server port
EXPOSE 3000

# Use the entrypoint script to initialize and start the application
ENTRYPOINT ["sh", "/usr/bin/entrypoint.sh"]
