default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  primary:
    <<: *default
    database: chat_api_development
  cache:
    <<: *default
    database: chat_api_development_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: chat_api_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: chat_api_test

production:
  primary:
    <<: *default
    database: 'chat_api'
  